// <auto-generated />
namespace PymeTamFinal.CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullableDescuento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableDescuento));
        
        string IMigrationMetadata.Id
        {
            get { return "201509211746161_nullableDescuento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
